---
# tasks file for kyoushi-simulation

# -------------------------------------------
# *** Install Requirements ***
# -------------------------------------------

- name: Add python repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
  when: kyoushi_venv_python_version < 3.8

- name: Ensure correct python version and python-pip is installed
  become: true
  ansible.builtin.apt:
    name:
      - python{{ kyoushi_venv_python_version }}
      - python3-pip
    update_cache: true

- name: Ensure virtualenv is installed
  become: true
  ansible.builtin.pip:
    name: virtualenv
    executable: pip3

# -------------------------------------------
# *** Setup kyoushi ***
# -------------------------------------------

- name: Ensure kyoushi base path exists
  become: true
  ansible.builtin.file:
    path: "{{ kyoushi_base_path }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    state: directory
    mode: "0755"

- name: Ensure venv path exists
  become: true
  ansible.builtin.file:
    path: "{{ kyoushi_venv_path }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    state: directory
    mode: "0755"
    recurse: true

- name: Install kyoushi packages
  become: true
  become_user: "{{ kyoushi_user_name | default(omit) }}"
  ansible.builtin.pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ kyoushi_venv_path }}"
    virtualenv_python: python{{ kyoushi_venv_python_version }}
    state: "{{ 'forcereinstall' if kyoushi_packages_reinstall else 'present' }}"
  loop: "{{ kyoushi_packages }}"

# HOTFIX: Copy static requirements.txt to host, using the ansible template
# module to avoid conflicts with fileglob when kyoushi files are copied

- name: Copy requirements file
  become: true
  ansible.builtin.template:
    src: requirements.txt
    dest: "{{ kyoushi_venv_path }}/requirements.txt"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    mode: "0755"

- name: Install kyoushi packages
  become: true
  become_user: "{{ kyoushi_user_name | default(omit) }}"
  ansible.builtin.pip:
    requirements: "{{ kyoushi_venv_path }}/requirements.txt"
    virtualenv: "{{ kyoushi_venv_path }}"
    virtualenv_python: python{{ kyoushi_venv_python_version }}
    state: forcereinstall
    extra_args: --no-deps # There are dependency-conflicts. Use this flag to force install.
  loop: "{{ kyoushi_packages }}"

- name: Set group to venv
  become: true
  ansible.builtin.file:
    path: "{{ kyoushi_venv_path }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    mode: "0755"

# -------------------------------------------
# *** Configure kyoushi ***
# -------------------------------------------

- name: Ensure state machine directory exists
  become: true
  ansible.builtin.file:
    path: "{{ kyoushi_sim_config_path }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    state: directory
    mode: "0755"

- name: Ensure log directory exists
  become: true
  ansible.builtin.file:
    path: "{{ kyoushi_log_file.path | dirname }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    state: directory
    mode: "0755"
    recurse: true
  when: kyoushi_log_file.path is defined

- name: Deploy config files
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    mode: "0755"
  loop: "{{ kyoushi_config_files.values() | list }}"
  when: item.deploy | default(true)

- name: Deploy optional state machine python plugin
  become: true
  ansible.builtin.copy:
    src: "{{ kyoushi_sm_python_plugin.src }}"
    dest: "{{ kyoushi_sm_python_plugin.dst }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    mode: "0755"
  when: kyoushi_sm_python_plugin is defined | default(false)

# -------------------------------------------
# *** Custom executable ***
# -------------------------------------------

- name: Ensure exec directory exists
  become: true
  ansible.builtin.file:
    path: "{{ kyoushi_exec_path }}"
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    state: directory
    mode: "0755"

- name: Deploy custom executable
  become: true
  ansible.builtin.template:
    src: "{{ kyoushi_executable_template }}"
    dest: "{{ kyoushi_venv_path }}/{{ kyoushi_sm_effective_name }}.sh" # hardcoded
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    mode: "0755"

- name: Create symlink to executable
  become: true
  ansible.builtin.file:
    src: "{{ kyoushi_venv_path }}/{{ kyoushi_sm_effective_name }}.sh"
    dest: /usr/local/bin/{{ kyoushi_sm_effective_name }}
    state: link
    owner: "{{ kyoushi_user_name | default(omit) }}"
    group: "{{ kyoushi_user_group | default(omit) }}"
    mode: "0755"
    force: true

- name: Create systemd service
  become: true
  ansible.builtin.template:
    src: "{{ kyoushi_service_template }}"
    dest: /etc/systemd/system/{{ kyoushi_sm_effective_name }}.service
    mode: "0644"
  notify: Systemctl daemon-reload
