---
# tasks file for kyoushi-simulation

# -------------------------------------------
# *** Install Requirements ***
# -------------------------------------------

- name: Add python repository
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
  when: kyoushi_venv_python_version < 3.8

- name: Ensure python {{ kyoushi_venv_python_version }} and python-pip is installed
  package:
    name: 
      - "python{{ kyoushi_venv_python_version }}"
      - python3-pip
    update_cache: yes

- name: Ensure virtualenv is installed
  pip:
    name: virtualenv
    executable: pip3


# -------------------------------------------
# *** Setup kyoushi ***
# -------------------------------------------

- name: Ensure kyoushi base path exists
  ansible.builtin.file:
    path: "{{ kyoushi_base_path }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
    state: directory

- name: Ensure venv path exists
  ansible.builtin.file:
    path: "{{ kyoushi_venv_path }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
    state: directory
    recurse: yes

- name: Install kyoushi packages
  pip:
    name: "{{ item.name }}{% if (item.version | default('latest')) != 'latest' %}=={{ item.version }}{%endif%}"
    extra_args: "--upgrade {% if item.url is defined %} --extra-index-url {{ item.url }}{%endif%}"
    virtualenv: "{{ kyoushi_venv_path }}"
    virtualenv_python: "{{ kyoushi_venv_python_version | string }}" 
  loop: "{{ kyoushi_packages }}"
  become: yes
  become_user: "{{ kyoushi_user_name }}"

- name: Set group to venv
  ansible.builtin.file:
    path: "{{ kyoushi_venv_path }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"


# -------------------------------------------
# *** Configure kyoushi ***
# -------------------------------------------

- name: Ensure state machine directory exists
  ansible.builtin.file:
    path: "{{ kyoushi_sim_config_path }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
    state: directory

- name: Ensure log directory exists
  ansible.builtin.file:
    path: "{{ kyoushi_log_file.path | dirname }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
    state: directory
    recurse: yes
  when: kyoushi_log_file.path is defined

- name: Deploy config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
  loop: "{{ kyoushi_config_files.values() | list }}"
  when: item.deploy | default(true)

- name: Deploy optional state machine python plugin
  ansible.builtin.copy:
    src: "{{ kyoushi_sm_python_plugin.src }}"
    dest: "{{ kyoushi_sm_python_plugin.dst }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
  when: kyoushi_sm_python_plugin is defined | default(false)


# -------------------------------------------
# *** Custom executable ***
# -------------------------------------------

- name: Deploy custom executable
  template:
    src: "sm_runner.sh.j2"
    dest: "/home/lreuter/{{ kyoushi_sm_name }}.sh"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
    mode: a+x