---
# tasks file for kyoushi-simulation

# -------------------------------------------
# *** Manage user ***
# -------------------------------------------

- name: Add group to system
  include_role:
    name: grog.group
  vars:
    group_list:
    - name: "{{ kyoushi_user_group }}"

- name: Add users to system
  include_role:
    name: grog.user
  vars:
    user_list:
    - name: "{{ kyoushi_user_name }}"
      groups: 
        - sudo
        - "{{ kyoushi_user_group }}"
      shell: "/bin/bash"
      password: "{{ kyoushi_user_password | password_hash('sha512') }}"

- name: Configure sudoers
  include_role: 
    name: grog.sudo
  vars:
    sudo_list: 
    - name: "{{ kyoushi_user_name }}"
      sudo: "{{ kyoushi_sudo_settings }}"


# -------------------------------------------
# *** Install Requirements ***
# -------------------------------------------

- name: Add python repository
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
  when: kyoushi_venv_python_version < 3.8

- name: Ensure python {{ kyoushi_venv_python_version }} and python-pip is installed
  package:
    name: 
      - "python{{ kyoushi_venv_python_version }}"
      - python3-pip
    update_cache: yes

- name: Ensure virtualenv is installed
  pip:
    name: virtualenv
    executable: pip3


# -------------------------------------------
# *** Setup kyoushi ***
# -------------------------------------------

- name: Ensure kyoushi base path exists
  ansible.builtin.file:
    path: "{{ kyoushi_base_path }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
    state: directory

- name: Install kyoushi packages
  pip:
    name: "{{ item.name }}"
    extra_args: "--upgrade --extra-index-url {{ item.url }}"
    virtualenv: "{{ kyoushi_venv_path }}"
    virtualenv_python: "{{ kyoushi_venv_python_version | string }}" 
  loop: "{{ kyoushi_packages }}"
  become: yes
  become_user: "{{ kyoushi_user_name }}"

- name: Set group to venv
  ansible.builtin.file:
    path: "{{ kyoushi_venv_path }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"


# -------------------------------------------
# *** Configure kyoushi ***
# -------------------------------------------

- name: Ensure state machine directory exists
  ansible.builtin.file:
    path: "{{ kyoushi_sim_config_path }}"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"
    state: directory

- name: Deploy simulation config file
  template:
    src: config.yml.j2
    dest: "{{ kyoushi_sim_config_path }}/config.yml"
    owner: "{{ kyoushi_user_name }}"
    group: "{{ kyoushi_user_group }}"